spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todo-list-graphql
        username: root
        password: ""
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            dll-auto: create-drop
        properties:
            javax:
                persistence:
                    schema-generation:
                        scripts:
                            action: create
                            create-target: create.sql
                            create-source: metadata